security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_CREATOR:     ROLE_CREATOR
        ROLE_VIDEO_CREATOR: ROLE_VIDEO_CREATOR
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
             entity:
                 class: App\Entity\User
                 property: username
    firewalls:
        dev:
             pattern: ^/(_(profiler|wdt)|css|images|js)/
             security: false
        main:
             lazy: true
             provider: app_user_provider
             form_login:
                 # "app_login" is the name of the route created previously
                 login_path: app_login
                 check_path: app_login
                 enable_csrf: true
             logout:
               path: app_logout
               target: /
    access_control:
        - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin$, role: ROLE_ADMIN }
        - { path: ^/profile$, role: ROLE_USER }
