version: "3.8"

services:
  nginx:
    container_name: nginx
    build:
      context: ./devops/nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    volumes:
      - ./:/var/www/html:rw
    depends_on:
      - php-fpm
    networks:
      - app-network
  php-fpm:
    container_name: php-fpm
    build:
      context: ./devops/php-fpm
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
  front:
    build:
      context: ./devops/node
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:rw
    ports:
      - '3000:3000'
    networks:
      - app-network
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql:
